'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Pago_Consolidado
    Protected WithEvents grd_PagoConsolidado As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents FecInicial As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents FecFinal As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents btn_Buscar As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btn_Export As Global.System.Web.UI.WebControls.Button


    Protected WithEvents SQL_pagoConsolidado As Global.System.Web.UI.WebControls.SqlDataSource
End Class
