'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Visits_Pers_aspx

    Protected WithEvents SQL_Personas As Global.System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents SQL_VisitaDetalle As Global.System.Web.UI.WebControls.SqlDataSource

    Protected WithEvents grd_Personas As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents grd_VisitaPersona As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents FecInicial As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents FecFinal As Global.System.Web.UI.WebControls.TextBox

End Class
