'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Gyms_Contactos

    Protected WithEvents grd_Contactos As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents SQL_Gyms As Global.System.Web.UI.WebControls.SqlDataSource
    Protected WithEvents TreeView1 As Global.System.Web.UI.WebControls.TreeView

End Class
